[package]
name = "td2-aaia"
version = "0.1.0"
authors = ["Loïc Rouquette <loic.rouquette@insa-lyon.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
